#!/bin/bash
/etc/init.d/netfilter-persistent restart
TEST=`systemctl status netfilter-persistent.service | tail -1 | grep "failed"`
if [[ -z "$TEST" ]]; then
 echo "No IPtables problems found."
 echo "IPtables now running."
else
 echo "Failed"
 iptables-restore /etc/iptables/rules.v4 2>/tmp/errorfile
 TEST=`cat /tmp/errorfile`
 LINENUM=`cat /tmp/errorfile | cut -f 2 -d ":" | tail -2 | head -n 1 | tr -d ' '`
 FQDN=`cat /tmp/errorfile | cut -f 1 -d "'" | head -n 1 | cut -f 4 -d " "`
 echo " "
 echo "******** 10-SECOND WARNING ALERT ***********"
 echo "IPtables FQDN problem on line: $LINENUM"
 echo "The unresolvable FQDN is $FQDN."
 echo "This rule will be disabled to allow IPtables to start."
 echo "Check and correct line $LINENUM in /etc/iptables/rules.v4."
 echo "******** 10-SECOND WARNING ALERT ***********"
 echo " "
 sed -i "$LINENUM s:^:#***:" /etc/iptables/rules.v4
 sleep 10
 /usr/local/sbin/iptables-restart
 exit
fi
/etc/init.d/fail2ban restart
/usr/local/sbin/iptables-custom
